In [2]:
#import libraries
import pandas as pd
import numpy as np
import yfinance as yf

#show big numbers with commas instead of scientific notation
pd.options.display.float_format = '{:,.0f}'.format

In [ ]:
ticker = yf.Ticker("AAPL")

df = yf.download(tickers= "AAPL", start= "2025-01-01", end="2025-12-31", group_by= "columns")
stockprice = df["AAPL"]["Close"]["2025-09-30"]

#Balance Sheet
bs = ticker.balance_sheet

#Income Statement
income_stmt = ticker.income_stmt

#CashFlow
cashflow = ticker.cashflow

[*********************100%***********************]  1 of 1 completed

np.float64(253.9116668701172)

In [4]:
#simple balance sheet 4 aapl

#Asset
cash = bs.loc["Cash And Cash Equivalents"]
accounts_receivable = bs.loc["Accounts Receivable"]
inventory = bs.loc["Inventory"]
net_ppe = bs.loc["Net PPE"]
total_assets = cash + accounts_receivable + inventory + net_ppe

#liabilities
accounts_payable = bs.loc["Accounts Payable"]
note_payable = bs.loc["Commercial Paper"]
long_term_debt = bs.loc["Long Term Debt"]
total_liabilites = accounts_payable + note_payable + long_term_debt

#equity
common_stock = bs.loc["Common Stock"]
retained_earnings = bs.loc["Retained Earnings"]
total_equity = common_stock + retained_earnings

In [5]:
#simple balance sheet as separate dataframes

simple_assets = pd.DataFrame({
    "cash": cash,
    "accounts receivable": accounts_receivable,
    "inventory": inventory,
    "net PPE": net_ppe,
    "total assets": total_assets
},index=["2025-09-30"])

simple_liabilities = pd.DataFrame({
    "accounts payable": accounts_payable,
    "notes payable": note_payable,
    "long term debt": long_term_debt,
    "total liabilities": total_liabilites
},index=["2025-09-30"])

simple_equity = pd.DataFrame({
    "common stock": common_stock,
    "retained earnings": retained_earnings,
    "total equity": total_equity
},index=["2025-09-30"])

print(simple_assets)
print(simple_equity)
print(simple_liabilities)

                     cash  accounts receivable     inventory        net PPE  \
2025-09-30 35,934,000,000       39,777,000,000 5,718,000,000 49,834,000,000

              total assets
2025-09-30 131,263,000,000
             common stock  retained earnings   total equity
2025-09-30 93,568,000,000    -14,264,000,000 79,304,000,000
            accounts payable  notes payable  long term debt  total liabilities
2025-09-30    69,860,000,000  7,979,000,000  78,328,000,000    156,167,000,000

In [6]:
#common-size statement 
common_assets = pd.DataFrame({
    "cash": cash/total_assets,
    "accounts receivable": accounts_receivable/total_assets,
    "inventory": inventory/total_assets,
    "net PPE": net_ppe/total_assets,
    "total assets": total_assets/total_assets
},index=["2025-09-30"])

common_liabilities = pd.DataFrame({
    "accounts payable": accounts_payable/total_liabilites,
    "notes payable": note_payable/total_liabilites,
    "long term debt": long_term_debt/total_liabilites,
    "total liabilities": total_liabilites/total_liabilites
},index=["2025-09-30"])

common_equity = pd.DataFrame({
    "common stock": common_stock/total_equity,
    "retained earnings": retained_earnings/total_equity,
    "total equity": total_equity/total_equity
},index=["2025-09-30"])

#ratios are between 0 and 1, so the notebook-wide "{:,.0f}" format (0 decimals)
#rounds everything to 0 or 1 -> show these as percentages instead
with pd.option_context('display.float_format', '{:.2%}'.format):
    print(common_assets)
    print(common_equity)
    print(common_liabilities)

             cash  accounts receivable  inventory  net PPE  total assets
2025-09-30 27.38%               30.30%      4.36%   37.97%       100.00%
            common stock  retained earnings  total equity
2025-09-30       117.99%            -17.99%       100.00%
            accounts payable  notes payable  long term debt  total liabilities
2025-09-30            44.73%          5.11%          50.16%            100.00%

In [18]:
#simple income statement
retained_earnings = bs.loc["Retained Earnings"]
addition_to_retained_earnings = retained_earnings - retained_earnings.shift(-1)

net_sales = income_stmt.loc["EBIT"] + income_stmt.loc["Cost Of Revenue"] + income_stmt.loc["Reconciled Depreciation"]

simple_income_statement = pd.DataFrame({
    "net sales" : net_sales,
    "cost of goods sold" : income_stmt.loc["Cost Of Revenue"],
    "depreciation" : income_stmt.loc["Reconciled Depreciation"],
    "EBIT" : income_stmt.loc["EBIT"],
    "interest paid" : income_stmt.loc["Interest Expense"],
    "EBT" : income_stmt.loc["Pretax Income"],
    "taxes" : income_stmt.loc["Tax Provision"],
    "net income" : income_stmt.loc["Net Income"],
    "dividends" : -cashflow.loc["Cash Dividends Paid"],
    "addition to retained earnings" : income_stmt.loc["Net Income"] + cashflow.loc["Cash Dividends Paid"]
}, index=["2023-09-30"])


# Apple's EBT (Pretax Income) doesn't exactly equal EBIT - interest paid,
# because it also includes interest income and other non-operating
# income/expense items that this simplified statement doesn't capture.


simple_income_statement.T

                                   2023-09-30
net sales                     339,957,000,000
cost of goods sold            214,137,000,000
depreciation                   11,519,000,000
EBIT                          114,301,000,000
interest paid                   3,933,000,000
EBT                           113,736,000,000
taxes                          16,741,000,000
net income                     96,995,000,000
dividends                      15,025,000,000
addition to retained earnings  81,970,000,000

In [22]:
#Common size income statement

common_income_statement = pd.DataFrame({
    "net sales" : net_sales/net_sales,
    "cost of goods sold" : income_stmt.loc["Cost Of Revenue"]/net_sales,
    "depreciation" : income_stmt.loc["Reconciled Depreciation"]/net_sales,
    "EBIT" : income_stmt.loc["EBIT"]/net_sales,
    "interest paid" : income_stmt.loc["Interest Expense"]/net_sales,
    "EBT" : income_stmt.loc["Pretax Income"]/net_sales,
    "taxes" : income_stmt.loc["Tax Provision"]/net_sales,
    "net income" : income_stmt.loc["Net Income"]/net_sales,
    "dividends" : -cashflow.loc["Cash Dividends Paid"]/net_sales,
    "addition to retained earnings" : (income_stmt.loc["Net Income"] + cashflow.loc["Cash Dividends Paid"])/net_sales
}, index=["2023-09-30"])


with pd.option_context('display.float_format', '{:.2%}'.format):
    print(common_income_statement.T)

                               2023-09-30
net sales                         100.00%
cost of goods sold                 62.99%
depreciation                        3.39%
EBIT                               33.62%
interest paid                       1.16%
EBT                                33.46%
taxes                               4.92%
net income                         28.53%
dividends                           4.42%
addition to retained earnings      24.11%

In [ ]:
pd.options.display.float_format = '{:.2f}'.format

In [48]:
###Financial ratio

##Liquidity Ratio

#Current Ratio
current_raito = bs.loc["Current Assets"]/bs.loc["Current Liabilities"]

#Quick Ratio
quick_ratio = (bs.loc["Current Assets"]-bs.loc["Inventory"])/bs.loc["Current Liabilities"]

#Cash Ratio
cash_ratio = bs.loc["Cash And Cash Equivalents"]/bs.loc["Current Liabilities"]


liquidity_ratio = pd.DataFrame({
    "current_raito":current_raito,
    "quick_ratio":quick_ratio,
    "cash_ratio":cash_ratio
}, index=["2023-09-30"])

liquidity_ratio.T

               2023-09-30
current_raito        0.99
quick_ratio          0.94
cash_ratio           0.21

In [54]:
##financial leverage ratio

#Total Debt Ratio 
total_debt_ratio = (total_assets - total_equity)/(total_assets)

#Debt-equity ratio 
debt_equity_ratio = total_liabilites / total_equity

#Equity Multiplier
equity_multiplier = total_assets / total_equity

#Long-term Debt ratio
long_term_debt_ratio = long_term_debt / (long_term_debt + total_equity)

#Times Interest Earned Ratio
tie_ratio = income_stmt.loc["EBIT"] / income_stmt.loc["Interest Expense"]

#Cash Coverage Ratio
cash_coverage_ratio = (income_stmt.loc["EBIT"] + income_stmt.loc["Reconciled Depreciation"]) / income_stmt.loc["Interest Expense"]

leverage_ratio = pd.DataFrame({
    "total_debt_ratio" : total_debt_ratio,
    "debt_equity_ratio" : debt_equity_ratio,
    "equity_multipier" : equity_multiplier,
    "long_term_debt_ratio" : long_term_debt_ratio,
    "tie_ratio" : tie_ratio,
    "cash_coverage_ratio" : cash_coverage_ratio 
}, index=["2023-09-30"])

leverage_ratio.T

                      2023-09-30
total_debt_ratio            0.33
debt_equity_ratio           2.23
equity_multipier            1.49
long_term_debt_ratio        0.56
tie_ratio                  29.06
cash_coverage_ratio        31.99

In [ ]:
##Asset Utilization Ratio

#Inventory Turnover 
inventory_turnover = income_stmt.loc["Cost Of Revenue"] / bs.loc["Inventory"]
#Days' Sales in Inventory
days_sales_in_inventory = 365/inventory_turnover

#Receivables Turnover Ratio
receivables_turnover_ratio = net_sales / accounts_receivable
#Days' Sales in Receivable Ratio
days_sales_in_receivable_ratio = 365/receivables_turnover_ratio

#NWC turnover ratio
nwc = bs.loc["Current Assets"] - bs.loc["Current Liabilities"]
nwc_turnover_ratio = net_sales / nwc

#Net PPE Turnover Ratio
net_ppe_turnover_ratio = net_sales/net_ppe

#Total Asset Turnover Ratio
total_asset_turnover_ratio = net_sales/total_assets


asset_utilization_ratio = pd.DataFrame({
    "inventory_turnover" : inventory_turnover,
    "days_sales_in_inventory" : days_sales_in_inventory,
    "receivables_turnover_ratio" : receivables_turnover_ratio,
    "days_sales_in_receivable_ratio" : days_sales_in_receivable_ratio,
    "nwc_turnover_ratio" : nwc_turnover_ratio,
    "net_ppe_turnover_ratio" : net_ppe_turnover_ratio,
    "total_asset_turnover_ratio" : total_asset_turnover_ratio
}, index = ["2025-09-30"])


asset_utilization_ratio.T

In [69]:
#Profitability measures
net_income = income_stmt.loc["Net Income"]

#Return On Sales(ROS)
ros = net_income / net_sales

#Return On Assets(ROA)
roa = net_income / total_assets

#Return On Equity(ROE)
roe = net_income / total_equity

profitability_measures = pd.DataFrame({
    "ros" : ros,
    "roa" : roa,
    "roe" : roe,
}, index = ["2025-09-30"])

profitability_measures.T

     2025-09-30
ros        0.31
roa        0.85
roe        1.41

In [ ]:
#Market Value Measures
pd.options.display.float_format = '{:,.0f}'.format

share_outstanding = income_stmt.loc["Basic Average Shares"]

#EPS
eps = net_income["2025-09-30"] / share_outstanding["2025-09-30"]

#PER
per = stockprice/eps

#PSR
psr = stockprice/(net_sales/share_outstanding)["2025-09-30"]

#PBR(price book-value ratio)
pbr = stockprice/(total_equity/share_outstanding)["2025-09-30"]

#Enterprise Value == Market Capitalization + Net Debt
market_capitalization = stockprice * share_outstanding["2025-09-30"]
net_debt = bs.loc["Total Debt"] - bs.loc["Cash And Cash Equivalents"]
ev = market_capitalization + net_debt
ev = ev["2025-09-30"]

#EBITDA = EBIT + Depreciation + Amortization
ebitda = income_stmt.loc["EBIT"] + income_stmt.loc["Reconciled Depreciation"]
ebitda = ebitda["2025-09-30"]

#EBiTA Ration
ebitda_ratio = ev/ebitda

market_value_measures = pd.DataFrame({
    "EPS" : eps,
    "PER" : per,
    "PSR" : psr,
    "PBR" : pbr,
    "EBITDA ratio" : ebitda_ratio
}, index=["2025-09-30"])

market_value_measures.T