In [16]:
#import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#we use yfinanace library 4 make example 
import yfinance as yf

#show big numbers with commas instead of scientific notation
pd.options.display.float_format = '{:,.0f}'.format

In [17]:
#call balance_sheet 2 Apple > All examples are provided with Apple's stock data
ticker = yf.Ticker("AAPL")

#yearly
bs = ticker.balance_sheet

#quarterly
bs_quarterly = ticker.quarterly_balance_sheet

print(bs)

#check index
bs.index.tolist()

                                                     2025-09-30  \
Treasury Shares Number                                      NaN
Ordinary Shares Number                           14,773,260,000
Share Issued                                     14,773,260,000
Net Debt                                         62,723,000,000
Total Debt                                       98,657,000,000
...                                                         ...
Cash Cash Equivalents And Short Term Investments 54,697,000,000
Other Short Term Investments                     18,763,000,000
Cash And Cash Equivalents                        35,934,000,000
Cash Equivalents                                  7,667,000,000
Cash Financial                                   28,267,000,000

                                                      2024-09-30  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                            15,116,786,000
Share Issued                                      15,116,786,000
Net Debt                                          76,686,000,000
Total Debt                                       106,629,000,000
...                                                          ...
Cash Cash Equivalents And Short Term Investments  65,171,000,000
Other Short Term Investments                      35,228,000,000
Cash And Cash Equivalents                         29,943,000,000
Cash Equivalents                                   2,744,000,000
Cash Financial                                    27,199,000,000

                                                      2023-09-30  \
Treasury Shares Number                                         0
Ordinary Shares Number                            15,550,061,000
Share Issued                                      15,550,061,000
Net Debt                                          81,123,000,000
Total Debt                                       111,088,000,000
...                                                          ...
Cash Cash Equivalents And Short Term Investments  61,555,000,000
Other Short Term Investments                      31,590,000,000
Cash And Cash Equivalents                         29,965,000,000
Cash Equivalents                                   1,606,000,000
Cash Financial                                    28,359,000,000

                                                      2022-09-30  2021-09-30
Treasury Shares Number                                       NaN         NaN
Ordinary Shares Number                            15,943,425,000         NaN
Share Issued                                      15,943,425,000         NaN
Net Debt                                          96,423,000,000         NaN
Total Debt                                       132,480,000,000         NaN
...                                                          ...         ...
Cash Cash Equivalents And Short Term Investments  48,304,000,000         NaN
Other Short Term Investments                      24,658,000,000         NaN
Cash And Cash Equivalents                         23,646,000,000         NaN
Cash Equivalents                                   5,100,000,000         NaN
Cash Financial                                    18,546,000,000         NaN

[69 rows x 5 columns]

['Treasury Shares Number',
 'Ordinary Shares Number',
 'Share Issued',
 'Net Debt',
 'Total Debt',
 'Tangible Book Value',
 'Invested Capital',
 'Working Capital',
 'Net Tangible Assets',
 'Capital Lease Obligations',
 'Common Stock Equity',
 'Total Capitalization',
 'Total Equity Gross Minority Interest',
 'Stockholders Equity',
 'Gains Losses Not Affecting Retained Earnings',
 'Other Equity Adjustments',
 'Retained Earnings',
 'Capital Stock',
 'Common Stock',
 'Total Liabilities Net Minority Interest',
 'Total Non Current Liabilities Net Minority Interest',
 'Other Non Current Liabilities',
 'Tradeand Other Payables Non Current',
 'Long Term Debt And Capital Lease Obligation',
 'Long Term Capital Lease Obligation',
 'Long Term Debt',
 'Current Liabilities',
 'Other Current Liabilities',
 'Current Deferred Liabilities',
 'Current Deferred Revenue',
 'Current Debt And Capital Lease Obligation',
 'Current Capital Lease Obligation',
 'Current Debt',
 'Other Current Borrowings',
 'Commercial Paper',
 'Payables And Accrued Expenses',
 'Current Accrued Expenses',
 'Payables',
 'Total Tax Payable',
 'Income Tax Payable',
 'Accounts Payable',
 'Total Assets',
 'Total Non Current Assets',
 'Other Non Current Assets',
 'Non Current Deferred Assets',
 'Non Current Deferred Taxes Assets',
 'Investments And Advances',
 'Other Investments',
 'Investmentin Financial Assets',
 'Available For Sale Securities',
 'Net PPE',
 'Accumulated Depreciation',
 'Gross PPE',
 'Leases',
 'Other Properties',
 'Machinery Furniture Equipment',
 'Land And Improvements',
 'Properties',
 'Current Assets',
 'Other Current Assets',
 'Inventory',
 'Receivables',
 'Other Receivables',
 'Accounts Receivable',
 'Cash Cash Equivalents And Short Term Investments',
 'Other Short Term Investments',
 'Cash And Cash Equivalents',
 'Cash Equivalents',
 'Cash Financial']

In [18]:
#net working capital = current asset - current liabilities

current_asset = bs.loc["Current Assets"]
current_liabilites = bs.loc["Current Liabilities"]

net_working_capital = current_asset - current_liabilites

print(net_working_capital)

2025-09-30   -17,674,000,000
2024-09-30   -23,405,000,000
2023-09-30    -1,742,000,000
2022-09-30   -18,577,000,000
2021-09-30               NaN
dtype: float64

In [19]:
# shareholder's equity = asset - liabilites
# asset - (equity + liabilites) = 0

total_asset = bs.loc["Total Assets"]
total_liabilites = bs.loc["Total Liabilities Net Minority Interest"]
total_equity = bs.loc["Total Equity Gross Minority Interest"]

check = total_asset - (total_equity + total_liabilites)

result = pd.DataFrame({
    "total asset": total_asset,
    "total equity": total_equity,
    "total liabilites": total_liabilites,
    "total equity + total liabilites" : total_liabilites + total_equity,
    "diff": check
    })

result

,total asset,total equity,total liabilites,total equity + total liabilites,diff
2025-09-30,"359,241,000,000","73,733,000,000","285,508,000,000","359,241,000,000",0
2024-09-30,"364,980,000,000","56,950,000,000","308,030,000,000","364,980,000,000",0
2023-09-30,"352,583,000,000","62,146,000,000","290,437,000,000","352,583,000,000",0
2022-09-30,"352,755,000,000","50,672,000,000","302,083,000,000","352,755,000,000",0
2021-09-30,NaN,NaN,NaN,NaN,NaN

In [20]:
# call income statement 4 Apple

#yearly
income_stmt = ticker.income_stmt

#quarterly
income_stmt_quarterly = ticker.quarterly_income_stmt

print(income_stmt)
income_stmt.index.tolist()

                                                        2025-09-30  \
Tax Effect Of Unusual Items                                      0
Tax Rate For Calcs                                               0
Normalized EBITDA                                  144,748,000,000
Net Income From Continuing Operation Net Minori... 112,010,000,000
Reconciled Depreciation                             11,698,000,000
Reconciled Cost Of Revenue                         220,960,000,000
EBITDA                                             144,748,000,000
EBIT                                               133,050,000,000
Net Interest Income                                            NaN
Interest Expense                                               NaN
Interest Income                                                NaN
Normalized Income                                  112,010,000,000
Net Income From Continuing And Discontinued Ope... 112,010,000,000
Total Expenses                                     283,111,000,000
Total Operating Income As Reported                 133,050,000,000
Diluted Average Shares                              15,004,697,000
Basic Average Shares                                14,948,500,000
Diluted EPS                                                      7
Basic EPS                                                        7
Diluted NI Availto Com Stockholders                112,010,000,000
Net Income Common Stockholders                     112,010,000,000
Net Income                                         112,010,000,000
Net Income Including Noncontrolling Interests      112,010,000,000
Net Income Continuous Operations                   112,010,000,000
Tax Provision                                       20,719,000,000
Pretax Income                                      132,729,000,000
Other Income Expense                                  -321,000,000
Other Non Operating Income Expenses                   -321,000,000
Net Non Operating Interest Income Expense                      NaN
Interest Expense Non Operating                                 NaN
Interest Income Non Operating                                  NaN
Operating Income                                   133,050,000,000
Operating Expense                                   62,151,000,000
Research And Development                            34,550,000,000
Selling General And Administration                  27,601,000,000
Gross Profit                                       195,201,000,000
Cost Of Revenue                                    220,960,000,000
Total Revenue                                      416,161,000,000
Operating Revenue                                  416,161,000,000

                                                        2024-09-30  \
Tax Effect Of Unusual Items                                      0
Tax Rate For Calcs                                               0
Normalized EBITDA                                  134,661,000,000
Net Income From Continuing Operation Net Minori...  93,736,000,000
Reconciled Depreciation                             11,445,000,000
Reconciled Cost Of Revenue                         210,352,000,000
EBITDA                                             134,661,000,000
EBIT                                               123,216,000,000
Net Interest Income                                            NaN
Interest Expense                                               NaN
Interest Income                                                NaN
Normalized Income                                   93,736,000,000
Net Income From Continuing And Discontinued Ope...  93,736,000,000
Total Expenses                                     267,819,000,000
Total Operating Income As Reported                 123,216,000,000
Diluted Average Shares                              15,408,095,000
Basic Average Shares                                15,343,783,000
Diluted EPS                                                      6
Basic EPS                                                        6
Diluted NI Availto Com Stockholders                 93,736,000,000
Net Income Common Stockholders                      93,736,000,000
Net Income                                          93,736,000,000
Net Income Including Noncontrolling Interests       93,736,000,000
Net Income Continuous Operations                    93,736,000,000
Tax Provision                                       29,749,000,000
Pretax Income                                      123,485,000,000
Other Income Expense                                   269,000,000
Other Non Operating Income Expenses                    269,000,000
Net Non Operating Interest Income Expense                      NaN
Interest Expense Non Operating                                 NaN
Interest Income Non Operating                                  NaN
Operating Income                                   123,216,000,000
Operating Expense                                   57,467,000,000
Research And Development                            31,370,000,000
Selling General And Administration                  26,097,000,000
Gross Profit                                       180,683,000,000
Cost Of Revenue                                    210,352,000,000
Total Revenue                                      391,035,000,000
Operating Revenue                                  391,035,000,000

                                                        2023-09-30  \
Tax Effect Of Unusual Items                                      0
Tax Rate For Calcs                                               0
Normalized EBITDA                                  125,820,000,000
Net Income From Continuing Operation Net Minori...  96,995,000,000
Reconciled Depreciation                             11,519,000,000
Reconciled Cost Of Revenue                         214,137,000,000
EBITDA                                             125,820,000,000
EBIT                                               114,301,000,000
Net Interest Income                                   -183,000,000
Interest Expense                                     3,933,000,000
Interest Income                                      3,750,000,000
Normalized Income                                   96,995,000,000
Net Income From Continuing And Discontinued Ope...  96,995,000,000
Total Expenses                                     268,984,000,000
Total Operating Income As Reported                 114,301,000,000
Diluted Average Shares                              15,812,547,000
Basic Average Shares                                15,744,231,000
Diluted EPS                                                      6
Basic EPS                                                        6
Diluted NI Availto Com Stockholders                 96,995,000,000
Net Income Common Stockholders                      96,995,000,000
Net Income                                          96,995,000,000
Net Income Including Noncontrolling Interests       96,995,000,000
Net Income Continuous Operations                    96,995,000,000
Tax Provision                                       16,741,000,000
Pretax Income                                      113,736,000,000
Other Income Expense                                  -565,000,000
Other Non Operating Income Expenses                   -565,000,000
Net Non Operating Interest Income Expense             -183,000,000
Interest Expense Non Operating                       3,933,000,000
Interest Income Non Operating                        3,750,000,000
Operating Income                                   114,301,000,000
Operating Expense                                   54,847,000,000
Research And Development                            29,915,000,000
Selling General And Administration                  24,932,000,000
Gross Profit                                       169,148,000,000
Cost Of Revenue                                    214,137,000,000
Total Revenue                                      383,285,000,000
Operating Revenue                                  383,285,000,000

                                                        2022-09-30  \
Tax Effect Of Unusual Items                                      0
Tax Rate For Calcs                                               0
Normalized EBITDA                                  130,541,000,000
Net Income From Continuing Operation Net Minori...  99,803,000,000
Reconciled Depreciation                             11,104,000,000
Reconciled Cost Of Revenue                         223,546,000,000
EBITDA                                             130,541,000,000
EBIT                                               119,437,000,000
Net Interest Income                                   -106,000,000
Interest Expense                                     2,931,000,000
Interest Income                                      2,825,000,000
Normalized Income                                   99,803,000,000
Net Income From Continuing And Discontinued Ope...  99,803,000,000
Total Expenses                                     274,891,000,000
Total Operating Income As Reported                 119,437,000,000
Diluted Average Shares                              16,325,819,000
Basic Average Shares                                16,215,963,000
Diluted EPS                                                      6
Basic EPS                                                        6
Diluted NI Availto Com Stockholders                 99,803,000,000
Net Income Common Stockholders                      99,803,000,000
Net Income                                          99,803,000,000
Net Income Including Noncontrolling Interests       99,803,000,000
Net Income Continuous Operations                    99,803,000,000
Tax Provision                                       19,300,000,000
Pretax Income                                      119,103,000,000
Other Income Expense                                  -334,000,000
Other Non Operating Income Expenses                   -334,000,000
Net Non Operating Interest Income Expense             -106,000,000
Interest Expense Non Operating                       2,931,000,000
Interest Income Non Operating                        2,825,000,000
Operating Income                                   119,437,000,000
Operating Expense                                   51,345,000,000
Research And Development                            26,251,000,000
Selling General And Administration                  25,094,000,000
Gross Profit                                       170,782,000,000
Cost Of Revenue                                    223,546,000,000
Total Revenue                                      394,328,000,000
Operating Revenue                                  394,328,000,000

                                                      2021-09-30
Tax Effect Of Unusual Items                                  NaN
Tax Rate For Calcs                                           NaN
Normalized EBITDA                                            NaN
Net Income From Continuing Operation Net Minori...           NaN
Reconciled Depreciation                                      NaN
Reconciled Cost Of Revenue                                   NaN
EBITDA                                                       NaN
EBIT                                                         NaN
Net Interest Income                                  198,000,000
Interest Expense                                   2,645,000,000
Interest Income                                    2,843,000,000
Normalized Income                                            NaN
Net Income From Continuing And Discontinued Ope...           NaN
Total Expenses                                               NaN
Total Operating Income As Reported                           NaN
Diluted Average Shares                                       NaN
Basic Average Shares                                         NaN
Diluted EPS                                                  NaN
Basic EPS                                                    NaN
Diluted NI Availto Com Stockholders                          NaN
Net Income Common Stockholders                               NaN
Net Income                                                   NaN
Net Income Including Noncontrolling Interests                NaN
Net Income Continuous Operations                             NaN
Tax Provision                                                NaN
Pretax Income                                                NaN
Other Income Expense                                         NaN
Other Non Operating Income Expenses                          NaN
Net Non Operating Interest Income Expense            198,000,000
Interest Expense Non Operating                     2,645,000,000
Interest Income Non Operating                      2,843,000,000
Operating Income                                             NaN
Operating Expense                                            NaN
Research And Development                                     NaN
Selling General And Administration                           NaN
Gross Profit                                                 NaN
Cost Of Revenue                                              NaN
Total Revenue                                                NaN
Operating Revenue                                            NaN

['Tax Effect Of Unusual Items',
 'Tax Rate For Calcs',
 'Normalized EBITDA',
 'Net Income From Continuing Operation Net Minority Interest',
 'Reconciled Depreciation',
 'Reconciled Cost Of Revenue',
 'EBITDA',
 'EBIT',
 'Net Interest Income',
 'Interest Expense',
 'Interest Income',
 'Normalized Income',
 'Net Income From Continuing And Discontinued Operation',
 'Total Expenses',
 'Total Operating Income As Reported',
 'Diluted Average Shares',
 'Basic Average Shares',
 'Diluted EPS',
 'Basic EPS',
 'Diluted NI Availto Com Stockholders',
 'Net Income Common Stockholders',
 'Net Income',
 'Net Income Including Noncontrolling Interests',
 'Net Income Continuous Operations',
 'Tax Provision',
 'Pretax Income',
 'Other Income Expense',
 'Other Non Operating Income Expenses',
 'Net Non Operating Interest Income Expense',
 'Interest Expense Non Operating',
 'Interest Income Non Operating',
 'Operating Income',
 'Operating Expense',
 'Research And Development',
 'Selling General And Administration',
 'Gross Profit',
 'Cost Of Revenue',
 'Total Revenue',
 'Operating Revenue']

In [21]:
#revenues - expenses = income

total_revenues = income_stmt.loc["Total Revenue"]
total_expenses = income_stmt.loc["Total Expenses"] + income_stmt.loc["Tax Provision"] 
    # There's no built-in "total expenses" field, so I added the tax provision manually
net_income = income_stmt.loc["Net Income"]

check = total_revenues - total_expenses

result = pd.DataFrame({'revenues': total_revenues,
                       'expenses' : total_expenses,
                       'income': net_income,
                       'diff' : check,
                       })

result

                  revenues        expenses          income            diff
2025-09-30 416,161,000,000 303,830,000,000 112,010,000,000 112,331,000,000
2024-09-30 391,035,000,000 297,568,000,000  93,736,000,000  93,467,000,000
2023-09-30 383,285,000,000 285,725,000,000  96,995,000,000  97,560,000,000
2022-09-30 394,328,000,000 294,191,000,000  99,803,000,000 100,137,000,000
2021-09-30             NaN             NaN             NaN             NaN

In [22]:
#simple income statement

# dividends is on cashflow, not income statement so I called cashflow
cashflow = ticker.cashflow

# and addition to retained Earnings is a cumulative balance, so the increase is computed
# by subtracting the prior period's balance from the current period's.
 
retained_earnings = bs.loc["Retained Earnings"]
addition_to_retained_earnings = retained_earnings - retained_earnings.shift(-1)


simple_income_statement = pd.DataFrame({
    "net sales" : income_stmt.loc["Total Revenue"],
    "cost of goods sold" : income_stmt.loc["Cost Of Revenue"],
    "depreciation" : income_stmt.loc["Reconciled Depreciation"],
    "EBIT" : income_stmt.loc["EBIT"],
    "interest paid" : income_stmt.loc["Interest Expense"],
    "EBT" : income_stmt.loc["Pretax Income"],
    "taxes" : income_stmt.loc["Tax Provision"],
    "net income" : income_stmt.loc["Net Income"],
    "dividends" : cashflow.loc["Cash Dividends Paid"],
    "addition to retained earnings" : addition_to_retained_earnings
})

check = (simple_income_statement["net income"] 
         + simple_income_statement["dividends"]   
         - simple_income_statement["addition to retained earnings"])

simple_income_statement["check"] = check
simple_income_statement

# A small gap can remain due to share buybacks and other equity adjustments
# (e.g. stock-based compensation) that aren't fully captured here.

,net sales,cost of goods sold,depreciation,EBIT,interest paid,EBT,taxes,net income,dividends,addition to retained earnings,check
2025-09-30,"416,161,000,000","220,960,000,000","11,698,000,000","133,050,000,000",NaN,"132,729,000,000","20,719,000,000","112,010,000,000","-15,421,000,000","4,890,000,000","91,699,000,000"
2024-09-30,"391,035,000,000","210,352,000,000","11,445,000,000","123,216,000,000",NaN,"123,485,000,000","29,749,000,000","93,736,000,000","-15,234,000,000","-18,940,000,000","97,442,000,000"
2023-09-30,"383,285,000,000","214,137,000,000","11,519,000,000","114,301,000,000","3,933,000,000","113,736,000,000","16,741,000,000","96,995,000,000","-15,025,000,000","2,854,000,000","79,116,000,000"
2022-09-30,"394,328,000,000","223,546,000,000","11,104,000,000","119,437,000,000","2,931,000,000","119,103,000,000","19,300,000,000","99,803,000,000","-14,841,000,000",NaN,NaN
2021-09-30,NaN,NaN,NaN,NaN,"2,645,000,000",NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#marginal tax rate calculator
tax_brackets = [
        (9875, 0.10),
        (40125, 0.12),
        (85525, 0.22),
        (163300, 0.24),
        (207350, 0.32),
        (518400, 0.35),
        (float("inf"), 0.37)
    ]

taxable_income = 10000000

def marginal_tax_rate(taxable_income):
    tax = 0
    lower = 0
    marginal_rate = None

    for upper, rate in tax_brackets:
        if taxable_income > lower:
            taxed_amount = min(taxable_income, upper) - lower
            tax += taxed_amount * rate
            marginal_rate = rate

        lower = upper
        if taxable_income <= upper:
            break

    average_rate = tax / taxable_income if taxable_income > 0 else 0
    
    return tax, marginal_rate, average_rate

tax, marginal_rate, average_rate = marginal_tax_rate(taxable_income)

print(taxable_income)
print("tax: ", tax)
print("marginal_rate: ", marginal_rate)
print("average_rate: ", average_rate)

10000000
tax:  3664427.0
marginal_rate:  0.37
average_rate:  0.3664427

In [26]:
#Cashflow
#cash flow from assets(CFFA) = cash flow from creditors(CFTC) + cash flow to stockholders(CFTS)

#CFFA is operating cash flow(OCF) - net capital spending(NCS) - net working captial(NWC)

#OCF is EBIT + Depreciation - Taxes
ocf = income_stmt.loc["EBIT"] + income_stmt.loc["Reconciled Depreciation"] - income_stmt.loc["Tax Provision"]

#NCS is Ending Net Fixed Assets - Beginning Net Fixed Assets + Depreciation
ncs = bs.loc["Net PPE"] - bs.loc["Net PPE"].shift(-1) + income_stmt.loc["Reconciled Depreciation"]

#NWC is Ending Working Captial - Beginning Working Capital
nwc = (bs.loc["Current Assets"] - bs.loc["Current Assets"].shift(-1)) - (bs.loc["Current Liabilities"] - bs.loc["Current Liabilities"].shift(-1))

cffa = ocf - ncs - nwc

#CFTC is Interest Paid - Net New Borrowing
#Net New Borrowing is Ending Long term Debt - Beginning Long term Debt
net_new_borrowing = bs.loc["Long Term Debt"] - bs.loc["Long Term Debt"].shift(-1)

cftc = income_stmt.loc["Interest Expense"] - net_new_borrowing

#CFTS is Dividends Paid - Net New Equity Raised
#Net New Equity is Ending Common Stock - Beginning Common Stock
net_new_equity = bs.loc["Common Stock"] - bs.loc["Common Stock"].shift(-1)

cfts = -cashflow.loc["Cash Dividends Paid"] - net_new_equity

check = cftc + cfts

if cffa == check:
    print("ok")
else:
    print("no")
    print("check")

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
print(cffa)